{
  parserClass="com.en_circle.slt.plugin.lisp.LispParser"
  parserUtilClass="com.en_circle.slt.plugin.lisp.LispParserUtil"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Lisp"
  psiImplClassSuffix="Impl"
  psiPackage="com.en_circle.slt.plugin.lisp.psi"
  psiImplPackage="com.en_circle.slt.plugin.lisp.impl"

  elementTypeHolderClass="com.en_circle.slt.plugin.lisp.psi.LispTypes"
  elementTypeClass="com.en_circle.slt.plugin.lisp.psi.LispElementType"
  tokenTypeClass="com.en_circle.slt.plugin.lisp.psi.LispTokenType"

  psiImplUtilClass="com.en_circle.slt.plugin.lisp.psi.impl.LispPsiImplUtil"
}

lispFile ::= sexpr* EOF

sexpr ::= sugar* (pair|list|atom|COMMENT)

list ::= LPAREN sexpr* RPAREN

pair ::= LPAREN sexpr+ DOT sexpr RPAREN

sugar ::= (QUOTE | BACKQUOTE | (COMMA AMPERSAND?) | (HASHTAG COMMA?))

atom ::= number | string | symbol

number ::= NUMBER_TOKEN

string ::= STRING_TOKEN

symbol ::= IDENTIFIER_TOKEN {
    mixin="com.en_circle.slt.plugin.lisp.psi.impl.LispNamedElementImpl"
  implements="com.en_circle.slt.plugin.lisp.psi.LispNamedElement"
  methods=[getName setName getNameIdentifier]
}